workspace:
  base: /go
  path: src/github.com/eirsyl/statuspage

pipeline:
  test:
    image: golang:onbuild
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - /go/bin/dep ensure
      - go test . ./src/...
      - go build